name: Android Fastlane Firebase Distribution

on:
    push:
        branches:
          - main
jobs:
  firebase_distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Repo Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.4'
          bundler-cache: true
          working-directory: android

      - name: Run Fastlane
        uses: wzieba/Fastlane-Github-Action@v3
        with:
          lane: docdoc_distribution

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DocDoc App
          path: build/app/outputs/apk/release